### Numpy

    Numpy stands for numerical python
    
    Fundamental package for numerical computations in Python
    
    Supports N-dimensional array objects that can be used for processing multidimensional data
    
    Supports different data-types


### Create array in numpy

### 1.Create array by using np.array( ) method

    Ordered collection of elements of basic data types of given length
    
    Syntax: numpy.array(object)


In [59]:
import numpy as np

In [2]:
L1=[1,2,3,4,5]
print(L1)
print(type(L1))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
a1=np.array(L1)    #List is converted into array

In [4]:
print(a1)

[1 2 3 4 5]


In [5]:
print(type(a1))

<class 'numpy.ndarray'>


In [7]:
#Create np array
a2=np.array([44,86,92,24,35,51])
print(a2)
print(type(a2))

[44 86 92 24 35 51]
<class 'numpy.ndarray'>


### Numpy statistical functions

In [14]:
array = np.array([45,89,62,12,74,32,56,44,65,99,1,15])
print(array)
print(type(array))

max_ele=np.max(array)
min_ele=np.min(array)
mean=np.mean(array)
median=np.median(array)
ptp=np.ptp(array)
std_dev=np.std(array)
variance=np.var(array)
average=np.average(array)


print("Max :",max_ele)
print("Min :",min_ele)
print("Mean :",mean)
print("Median :",median)
print("ptp :",ptp)
print("Standard deviation :",std_dev)
print("Variance:",variance)

[45 89 62 12 74 32 56 44 65 99  1 15]
<class 'numpy.ndarray'>
Max : 99
Min : 1
Mean : 49.5
Median : 50.5
ptp : 98
Standard deviation : 29.37544325906703
Variance: 862.9166666666666


In [16]:
arr1=np.array([70,99,85,42,12,32,61])
arr2=np.array([20,22,21,23,20,21,22])

std_1=np.std(arr1)
std_2=np.std(arr2)
print(std_1)   #less Similarity in data , more the variance
print(std_2)   #More similarity in data , less the variance

28.303025005991778
1.0301575072754254


In [67]:
#Percentile
array = np.array([45,89,62,12,74,32,56,44,65,99,1,15])
Q1=(np.min(array))             #First Quartile gives minimum value
Q2=(np.percentile(array,25))   #Second Quartile
Q3=(np.percentile(array,50))   # Third quartile gives Median
Q4=(np.percentile(array,75))   #Fourth Quartile
Q5=(np.max(array))             #Fifth quartile gives maximum value

In [70]:
print(Q1)
print(Q2)
print(Q3)
print(Q4)
print(Q5)

1
27.75
50.5
67.25
99


In [71]:
IQR=Q3-Q1

In [72]:
IQR  #Inter-Quartile Range(Diffrence between third and first quartile)

49.5

##### Note: Numpy array can handle different categorical entities
##### All elements are coerced(converted) to same data type



In [20]:
arr1=np.array([2,3,5.6,'n'])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'n']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>



### 2. Generate Array using linespace

    numpy.linspace()- returns equally spaced numbers within the given range based on the sample number
    
##### Syntax:numpy.linspace(start,stop,num)
        
##### start - start of interval range
    
##### stop - end of interval range
    
##### num - number of samples to be generated



In [21]:
arr2=np.linspace(0,90,6)    #In linspace third element is that how many numbers we have to generate
print(arr2)
arr3=np.linspace(0,90,6,retstep=True)
print(arr3)

[ 0. 18. 36. 54. 72. 90.]
(array([ 0., 18., 36., 54., 72., 90.]), 18.0)


In [22]:
# Generate an array b with start=1 and stop=5, also return step/diffrence
b=np.linspace(start=1,stop=5,num=10,retstep=True)
print(b)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)



### 3. Generate arrays using arange( )

    numpy.arange()- returns equally spaced numbers with in the given range based on step size
    
    Syntax:numpy.arange(start,stop,step)
        
    start - start of interval range
    
    stop - end of interval range
    
    step - step size of interval



In [25]:
#In arange method the third element is that diffrence between one elemrnt and next element
arr4=np.arange(10)   # start
print("arr4:",arr4)
arr5=np.arange(10,20)  # start, stop
print("arr5:",arr5)
arr6=np.arange(10,20,3)  # start, stop, step
print("arr6:",arr6)


arr4: [0 1 2 3 4 5 6 7 8 9]
arr5: [10 11 12 13 14 15 16 17 18 19]
arr6: [10 13 16 19]


In [30]:
array=np.arange(900,100,-10)
print(array)

[900 890 880 870 860 850 840 830 820 810 800 790 780 770 760 750 740 730
 720 710 700 690 680 670 660 650 640 630 620 610 600 590 580 570 560 550
 540 530 520 510 500 490 480 470 460 450 440 430 420 410 400 390 380 370
 360 350 340 330 320 310 300 290 280 270 260 250 240 230 220 210 200 190
 180 170 160 150 140 130 120 110]



### 4. Generate arrays using ones

    numpy.ones()- returns an array of given shape and type filled with ones
    
    Syntax:numpy.ones(shape,dtype)
        
    shape - integer or sequence of integers
    
    dtype - data type (default:float)

In [37]:
arr7=np.ones(6)
print(arr7)
print(arr7.ndim)

[1. 1. 1. 1. 1. 1.]
1


In [36]:
arr8=np.ones((3,4))
print(arr8)
print(arr8.ndim)   #Gives Dimentions

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2



### 5. Generate arrays using zeros

    numpy.zeros()- returns an array of given shape and type filled with zeros
    
    Syntax:numpy.zeros(shape,dtype)
        
    shape - integer or sequence of integers
    
    dtype - data type (default:float)

In [38]:
arr8=np.zeros(5)
print(arr8)

[0. 0. 0. 0. 0.]


In [42]:
arr=np.zeros((8,9))
print(arr)
print(arr.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2



### 6. Generate arrays using random.rand( )

    numpy.random.rand()- returns an array of given shape filled with random values
    
    Syntax:numpy.random.rand(shape)
        
    shape - integer or sequence of integers

In [44]:
arr9=np.random.rand(5)
print(arr9)

[0.72458247 0.48397503 0.99890984 0.10300081 0.56675424]


In [45]:
arr10=np.random.rand(7,5)
print(arr10)   #if we not specify range of numbers by default it is in range 0 to 1

[[0.24048238 0.08986259 0.37802576 0.85059336 0.34165407]
 [0.53747105 0.3081673  0.22170797 0.75457673 0.60297792]
 [0.4264272  0.45132334 0.94583066 0.0568765  0.05313255]
 [0.37788061 0.66145063 0.44690919 0.2933784  0.90795287]
 [0.34325899 0.0966825  0.82334318 0.60593309 0.68694881]
 [0.63329224 0.56672388 0.81649418 0.13517478 0.57118343]
 [0.70967931 0.44323338 0.98380828 0.87128117 0.8894368 ]]


In [47]:
#Select 5 random integers from the range of 1 to 100

arr12=np.random.randint(1,100,(5,3))
print("arr12:\n",arr12)
print(arr12.size)
print(arr12.shape)

arr12:
 [[68 81  3]
 [50 93 55]
 [81 75 26]
 [18 21  8]
 [46 16 35]]
15
(5, 3)



### 7. Generate arrays using logspace( )

    numpy.logspace()- returns equally spaced numbers based on log scale
    
    Syntax: numpy.logspace(start,stop,num,endpoint,base,dtype)
    start, stop,
    
    num - number of samples to generate (default :50),
    
    endpoint- if true, stop is the last sample,
    
    base - base of the log space (default :10.0),
    
    dtype- type of output array

In [48]:
np.logspace(start=1,stop=10,num=5,endpoint=True, base=10)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

### Advatages of Numpy

##### Speed : 
Array operations are carried out in C and hence the universal functions in numpy are faster than operations carried out on python lists
   

In [49]:
import time

In [54]:
py_list=[i for i in range (100000)]

In [56]:
start=time.time()
py_list=[i+2 for i in py_list]
stop=time.time()

print(stop-start)

0.004687070846557617


In [64]:
#By using numpy
py_array=np.array([i for i in range (100000)])

In [65]:
start=time.time()
py_array=py_array+2
stop=time.time()

print(stop-start)   #Requires less time therefore speed is fast

0.0003044605255126953


##### Storage Space :
Note that numpy array uses less bytes for storage than the python list


In [66]:
import sys

In [70]:
l1=[i for i in range (100)]
print(len(l1))

print(" Total size required to store l1= ",sys.getsizeof(l1[0])*len(l1))

100
 Total size required to store l1=  2400


In [71]:
a1=np.arange(100)
print("Total size required to store a1 =",a1.itemsize*100)

Total size required to store a1 = 800


### Operations on Array

##### 1.Check Shape of Array

In [75]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
print(a.shape)

(3, 3)


In [77]:
print(a.size)

9


In [78]:
np.sum(a,axis=0)  #Sum of columns

array([12, 15, 18])

In [79]:
np.sum(a,axis=1) #Sum of rows

array([ 6, 15, 24])

In [80]:
np.sum(a1)

4950


##### 2. Reshaping Size of Array

    reshape()- recasts an array to new shape without changing it’s data



In [89]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)

[[1 2 3 4]
 [6 7 8 9]]


In [90]:
b = a.reshape(4,2)
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]
(4, 2)


In [91]:
c=np.arange(51,69).reshape(6,3)
print(c)

[[51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]]


##### 3. Accessing Elements

In [96]:
# print 53 in c array
print(c[0][2])
# print 55 in c array
print(c[1,1])

53
55


In [97]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
# Access 2nd and 3rd row from a
print()
print(a[1:3])
# Access 1st and 3rd column from a
print()
print(a[:,(0,2)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]


In [98]:
#Take two arrays for further operations
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a1)
print()
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


##### 4. Numpy Addition

In [101]:
print("a+b = \n",np.add(a1,a2))

a+b = 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


##### 5. Numpy Substraction

In [103]:
print("a-b = \n",np.subtract(a1,a2))

a-b = 
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


##### 6. Numpy Multiplication

In [104]:
print("a*b = \n",np.multiply(a1,a2))

a*b = 
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


##### 7. Numpy Division

In [107]:
print("a/b = \n",np.divide(a2,a1))

a/b = 
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


##### 8. Remainder

In [108]:
print("a%b=\n",np.remainder(a2,a1))

a%b=
 [[0 0 1]
 [2 0 4]
 [3 2 1]]


##### 9. Numpy Transpose

In [109]:
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [115]:
print(np.transpose(a1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


##### 10. Numpy Append

In [117]:
print(a)
print()
print(np.append(a,[[10,11,12]],axis=0)) #Elements are added in columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [119]:
print(a2)
# To append in rows, transpose horizontal array to vertical array
c=np.array([[13,14,15]])
c=np.transpose(c)
print(c)
d=np.append(a2,c,axis=1) #Elements are added in rows
print(d)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[13]
 [14]
 [15]]
[[11 12 13 13]
 [14 15 16 14]
 [17 18 19 15]]


##### 11. Numpy Insert

In [120]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a=\n",a)
a_ins=np.insert(a,1,[[11,12,13]],axis=0)
print("a_ins=\n",a_ins)

a=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a_ins=
 [[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [ 7  8  9]]


##### 12. Numpy Delete

In [121]:
print("a_ins=\n",a_ins)


a_ins=
 [[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [ 7  8  9]]


In [122]:
a_del=np.delete(a_ins,1,axis=0)
print(a_del)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### How to create scalar in numpy

In [127]:
import numpy as np
a1=np.array([8])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.size)    

[8]
<class 'numpy.ndarray'>
(1,)
1


In [130]:
scalar_a1=np.asscalar(a1)

<ipython-input-130-f5645744cc6a>:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  scalar_a1=np.asscalar(a1)


In [131]:
print(scalar_a1)

8


In [132]:
print(type(scalar_a1))

<class 'int'>


##### How to create vector in numpy

In [3]:
import numpy as np
l1=([1,2,3,4])
l2=([12],
   [13],
   [14])

In [4]:
v1=np.array(l1)
v2=np.array(l2)

In [6]:
v1

array([1, 2, 3, 4])

In [7]:
v2

array([[12],
       [13],
       [14]])

### Matrices

Rectangular arrangement of numbers in rows and columns

Rows run horizontally and columns run vertically



##### How to create and work with matrix

matrix()- returns a matrix from an array type object or string of data

Syntax:numpy.matrix(data)



In [10]:
m1=np.matrix('1,2;3,4')

In [11]:
m1

matrix([[1, 2],
        [3, 4]])

In [12]:
type(m1)

numpy.matrix

In [13]:
print(m1[1,1])  #Access elements

4


##### Matrix Addition

In [21]:
m1=np.matrix("1,2,3;4,5,6;7,8,9")
m2=np.matrix("11,12,13;14,15,16;17,18,19")

In [22]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

##### Matrix Addition

    numpy.add(matrix_1,matrix_2)



In [24]:
print(np.add(m1,m2))

[[12 14 16]
 [18 20 22]
 [24 26 28]]


##### Matrix Subtraction

    numpy.subtract(m1,m2)



In [27]:
print(np.subtract(m2,m1))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


##### Matrix Multiplication
 Two ways = 1)numpy.dot(matrix1,matrix2)
    
            2)numpy.multiply(matrix1,matrix2)

In [30]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [28]:
print(np.dot(m1,m2))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [29]:
# Matrix multiplication element wise
print(np.multiply(m1,m2))

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


##### Matrix Division

    numpy.divide(matrix_1,matrix_2)



In [33]:
print(np.divide(m2,m1))

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


### Linear Algeabra : numpy.linalg

##### Determinent of Matrix

In [38]:
det_1=np.linalg.det(m1)
det_1

6.66133814775094e-16

In [39]:
det_2=np.linalg.det(m2)
det_2

-1.5987211554602137e-14

##### Rank of Matrix

In [37]:
rank_m1=np.linalg.matrix_rank(m1)
rank_m1

2

##### Inverse of Matrix

In [40]:
inv_m1=np.linalg.inv(m1)
inv_m1
# Inverse possible if matrix is non singular(Determinent Non-Zero)


matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

### Systems of Linear Equations

In [42]:
#Take two equations: 2x-y=-1 and 3x+2y=9
#Lets solve these equations

In [51]:
A=np.matrix('2,-1;3,2')
B=np.matrix('-1;9')

In [52]:
A

matrix([[ 2, -1],
        [ 3,  2]])

In [53]:
B

matrix([[-1],
        [ 9]])

In [54]:
Result=np.linalg.solve(A,B)

In [55]:
Result

matrix([[1.],
        [3.]])

In [57]:
#Lets take another example and Find Values of x,y,z
#3x+y+2z=2 , 3x+2y+5z=-1 , 6x+7y+8z=3
C=np.matrix("3,1,2;3,2,5;6,7,8")
D=np.matrix("2;-1;3")

In [59]:
C

matrix([[3, 1, 2],
        [3, 2, 5],
        [6, 7, 8]])

In [60]:
D

matrix([[ 2],
        [-1],
        [ 3]])

In [61]:
Result=np.linalg.solve(C,D)

In [63]:
print("The Value of x,y,z are :\n" ,Result,"Respectively")

The Value of x,y,z are :
 [[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]] Respectively


### Array broadcasting in Numpy

In [73]:
array1=np.array([11,22,33])

In [74]:
array2=np.array([5])

In [77]:
print(array1)
print(len(array1))

[11 22 33]
3


In [78]:
print(array2)
print(len(array2))

[5]
1


In [88]:
array3=array1*array2
#     11 22 33  * 5 5 5    ->Broadcasting of array(Array2 is broadcast array)
array3

array([ 55, 110, 165])

In [93]:
print(len(array3))
print(type(array3))
print(array3)

3
<class 'numpy.ndarray'>
[ 55 110 165]


###### Numpy Sorting Arrays

Sorting means putting elements in an ordered sequence.

In [94]:
array=np.array([11,2,45,61,25,98,75,43])
array

array([11,  2, 45, 61, 25, 98, 75, 43])

In [95]:
print(np.sort(array))

[ 2 11 25 43 45 61 75 98]


In [98]:
array1=(["Banana","Mango","Apple","Orange","Grapes"])
array1

['Banana', 'Mango', 'Apple', 'Orange', 'Grapes']

In [99]:
print(np.sort(array1))

['Apple' 'Banana' 'Grapes' 'Mango' 'Orange']


In [100]:
arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


In [101]:
#Sorting 2-D Array

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [102]:
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
# Get a sorted copy of numpy array (Descending Order)
arr = np.sort(arr)[::-1]
print('Sorted Array in Descending Order: ', arr)

Sorted Array in Descending Order:  [18 11  9  8  6  4  4  3  2  2  1]


In [105]:
# Sort Using 'mergesort'
sortedArr1 = np.sort(arr, kind='mergesort')
 
# Sort Using 'heapsort'
sortedArr2 = np.sort(arr, kind='heapsort')

# Sort Using 'heapsort'
sortedArr3 = np.sort(arr, kind='stable')

In [106]:
print(sortedArr1)
print(sortedArr2)
print(sortedArr3)

[ 1  2  2  3  4  4  6  8  9 11 18]
[ 1  2  2  3  4  4  6  8  9 11 18]
[ 1  2  2  3  4  4  6  8  9 11 18]


In [107]:
#Sorting 2-D array along axis
# Create a 2D Numpy array list of list
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1], [29, 32, 11, 9]])

In [108]:
arr2D

array([[ 8,  7,  1,  2],
       [ 3,  2,  3,  1],
       [29, 32, 11,  9]])

In [109]:
# Sort along axis 0 i.e. sort contents of each Column in numpy array
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]


In [110]:
# Sort along axis 1 i.e. sort contents of each Row in numpy array
arr2D.sort(axis=1)
print('Sorted Array : ')
print(arr2D)

Sorted Array : 
[[ 1  1  2  3]
 [ 2  3  7  8]
 [ 9 11 29 32]]


In [111]:
def main():
    # Create a Numpy array from list of numbers
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    print('Original Array : ', arr)
    
    print('*** Sort a Numpy Array inplace ***')
    # Sort the numpy array inplace
    arr.sort()
    print('Sorted Array : ', arr)
    
    print('*** Get a Sorted copy of a Numpy Array ***')
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    # To Get a sorted copy of numpy array (Ascending Order)
    sortedArr = np.sort(arr)
    print('Sorted Array : ', sortedArr)
    print('Original Array : ', arr)
    
    print('*** Sort a Numpy Array in Descending Order ***')
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    # Get a sorted copy of numpy array (Descending Order)
    arr = np.sort(arr)[::-1]
    print('Sorted Array in Descending Order: ', arr)
    
    # Sort Using 'mergesort'
    sortedArr = np.sort(arr, kind='mergesort')
    print('Sorted Array : ', sortedArr)
    
    # Sort Using 'heapsort'
    sortedArr = np.sort(arr, kind='heapsort')
    print('Sorted Array : ', sortedArr)
    print('*** Sorting 2D numpy array along axis ***')
    
    # Create a 2D Numpy array list of list
    arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1], [29, 32, 11, 9]])
    print('2D Numpy Array')
    print(arr2D)
    
    print('*** Sort Contents of each Column in 2D numpy Array | Sorting along axis 0 ***')
    # Sort along axis 0 i.e. sort contents of each Column in numpy array
    arr2D.sort(axis=0)
    print('Sorted Array : ')
    print(arr2D)
    
    print('*** Sort Contents of each Row in 2D numpy Array | Sorting along axis 1 ***')
    # Sort along axis 1 i.e. sort contents of each Row in numpy array
    arr2D.sort(axis=1)
    print('Sorted Array : ')
    print(arr2D)
    
if __name__ == '__main__':
  main()

Original Array :  [ 6  1  4  2 18  9  3  4  2  8 11]
*** Sort a Numpy Array inplace ***
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
*** Get a Sorted copy of a Numpy Array ***
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
Original Array :  [ 6  1  4  2 18  9  3  4  2  8 11]
*** Sort a Numpy Array in Descending Order ***
Sorted Array in Descending Order:  [18 11  9  8  6  4  4  3  2  2  1]
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
*** Sorting 2D numpy array along axis ***
2D Numpy Array
[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
*** Sort Contents of each Column in 2D numpy Array | Sorting along axis 0 ***
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]
*** Sort Contents of each Row in 2D numpy Array | Sorting along axis 1 ***
Sorted Array : 
[[ 1  1  2  3]
 [ 2  3  7  8]
 [ 9 11 29 32]]


### Case study on Numpy

In [113]:
import numpy as np

In [122]:
### First Step :- Load data
data=np.loadtxt("/home/divyasale/Downloads/cric.tsv",skiprows=1)

In [123]:
data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [138]:
Sachin_Data=data[:,1]
Dravid_Data=data[:,2]
India_data=data[:,3]

In [139]:
Sachin_Data

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [140]:
Dravid_Data

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [162]:
India_data

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

### 1.Find Mean and Median of Sachin, Dravid and India

In [149]:
#For Sachin
print("Mean of Sachin is : ",Sachin_Data.mean() ,"\nand Median of Sachin is : ",np.median(Sachin_Data))

Mean of Sachin is :  63.6 
and Median of Sachin is :  71.0


In [150]:
#For Dravid
print("Mean of Dravid is : ",Dravid_Data.mean() ,"\nand Median of Dravid is : ",np.median(Dravid_Data))

Mean of Dravid is :  71.06666666666666 
and Median of Dravid is :  74.0


In [151]:
#For India
print("Mean of India is : ",India_data.mean() ,"\nand Median of India is : ",np.median(India_data))

Mean of India is :  281.26666666666665 
and Median of India is :  288.0


### 2. How many centuries did Sachin and Dravid Score


In [155]:
#For Sachin
Sachin_centuries = np.count_nonzero(Sachin_Data>99)

In [156]:
print(Sachin_centuries)

4


In [157]:
#For Dravid
Dravid_centuries = np.count_nonzero(Dravid_Data>99)

In [158]:
print(Dravid_centuries)

3


In [166]:
Total_India_Century = np.count_nonzero(India_data>300)

In [167]:
print(Total_India_Century )

7


##### 3.How many matches did Sachin and Dravid takes to reach 500

In [168]:
#For sachin
sachin_score=np.cumsum(Sachin_Data)

In [169]:
np.searchsorted(sachin_score,500)

11

In [171]:
#For Dravid
dravid_score=np.cumsum(Dravid_Data)
np.searchsorted(dravid_score,500)

7